# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenSCAD中文站
email: lich.wang@gmail.com
description: 
url: "https://openscad.tech" # the base hostname & protocol for your site, e.g. http://example.com
favicon_ico: "/assets/images/openscad.png"
github_username:  lich-wang
repository: "openscad-cn/openscad-cn.github.io"

# Build settings
#theme: jekyll-theme-minimal
#remote_theme: sighingnow/jekyll-gitbook
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-readme-index
  - jemoji

search_enabled: false


collections:
  OpenSCAD-Tutorial:
    output: true
    sort_by: order
    permalink: /OpenSCAD-Tutorial/:path/

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    OpenSCAD-Tutorial:
      # Give the collection a name
      name: OpenSCAD教程

callouts_level: quiet # or loud
callouts:
  ex:
    title: 练习
    color: blue
  new:
    title: 知识点
    color: green
  note:
    title: 注意
    color: red
  code:
    title: 示例代码
    color: yellow

enable_copy_code_button: false


kramdown:
  syntax_highlighter_opts:
    default_lang: "cpp"
    block:
      line_numbers: false
  math_engine: mathjax
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


aux_links:
  "openscad.tech on GitHub":
    - "//github.com/openscad-cn/openscad-cn.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_enabled: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/openscad-cn/openscad-cn.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
